/**
 * DEVELOPMENT-ONLY demo data. Every record here carries `isDemo: true` and
 * demo-labeled titles so it can never be mistaken for (or shipped as) real
 * catalog/customers/reviews. Production deployments run against Supabase
 * with this module unused (see services/index.ts) — and the seeded demo
 * review data must never be inserted into a production database.
 *
 * Product artwork is original, neutral placeholder imagery generated by
 * scripts/generate-demo-images.mjs — no club badges, sponsor marks or
 * protected designs (spec §30).
 */
import type {
  CategoryDef,
  Customer,
  Order,
  PatchDef,
  Product,
  Review,
  ShippingZone,
  SizeChart,
  StoreSettings,
} from "../types.ts";

const L = (ar: string, he: string, en: string) => ({ ar, he, en });

export const ADULT_SIZES = ["S", "M", "L", "XL", "2XL"];
export const KIDS_SIZES = ["16", "18", "20", "22", "24", "26", "28"];

/* ── Categories (spec §8) ─────────────────────────────────────────────────── */
export const demoCategories: CategoryDef[] = [
  {
    slug: "retro",
    name: L("قمصان ريترو", "חולצות רטרו", "Retro Jerseys"),
    description: L("قطع من عصور ذهبية — قصّات وأجواء التسعينات والألفينات.", "פריטים מתקופות זהב — גזרות ואווירה של שנות ה־90 וה־2000.", "Pieces from golden eras — cuts and atmosphere of the 90s and 2000s."),
    basePriceIls: 170,
    sizeChartId: "retro",
    image: "/demo/cat-retro.webp",
    sortOrder: 1,
  },
  {
    slug: "current-season",
    name: L("الموسم الحالي", "העונה הנוכחית", "Current Season"),
    description: L("تشكيلات هذا الموسم — نسخ مشجعين ولاعبين.", "הקולקציות של העונה — גרסאות אוהד ושחקן.", "This season's kits — fan and player versions."),
    basePriceIls: 140,
    sizeChartId: "fan",
    image: "/demo/cat-current.webp",
    sortOrder: 2,
  },
  {
    slug: "national-teams",
    name: L("منتخبات", "נבחרות", "National Teams"),
    description: L("قمصان منتخبات مختارة من بطولات لا تُنسى.", "חולצות נבחרות מטורנירים בלתי נשכחים.", "National-team shirts from unforgettable tournaments."),
    basePriceIls: 140,
    sizeChartId: "fan",
    image: "/demo/cat-national.webp",
    sortOrder: 3,
  },
  {
    slug: "player-version",
    name: L("نسخة اللاعب", "גרסת שחקן", "Player Version"),
    description: L("خامة المباريات — قصّة ضيقة وتفاصيل أدق.", "בד המשחקים — גזרה צמודה ופרטים מדויקים.", "Match-grade fabric — athletic cut and finer detail."),
    basePriceIls: 160,
    sizeChartId: "player",
    image: "/demo/cat-player.webp",
    sortOrder: 4,
  },
  {
    slug: "fan-version",
    name: L("نسخة المشجع", "גרסת אוהד", "Fan Version"),
    description: L("راحة يومية بقصّة عادية — الخيار الكلاسيكي.", "נוחות יומיומית בגזרה רגילה — הבחירה הקלאסית.", "Everyday comfort in a regular cut — the classic choice."),
    basePriceIls: 140,
    sizeChartId: "fan",
    image: "/demo/cat-fan.webp",
    sortOrder: 5,
  },
  {
    slug: "long-sleeve",
    name: L("أكمام طويلة", "שרוול ארוך", "Long Sleeve"),
    description: L("ليالي الشتاء والملاعب المفتوحة — أكمام كاملة.", "ללילות קרים וליציעים פתוחים — שרוול מלא.", "For cold nights and open stands — full sleeves."),
    basePriceIls: 175,
    sizeChartId: "long-sleeve",
    image: "/demo/cat-longsleeve.webp",
    sortOrder: 6,
  },
  {
    slug: "hoodies",
    name: L("هوديز كرة القدم", "הודיס כדורגל", "Football Hoodies"),
    description: L("طبقة الشارع — دفء بهوية كروية.", "שכבת הרחוב — חום עם זהות כדורגל.", "The street layer — warmth with football identity."),
    basePriceIls: 250,
    sizeChartId: "hoodie",
    image: "/demo/cat-hoodie.webp",
    sortOrder: 7,
  },
  {
    slug: "kids",
    name: L("أطقم أطفال", "סטים לילדים", "Kids' Sets"),
    description: L("أطقم كاملة بمقاسات صغيرة — للجيل القادم.", "סטים מלאים במידות קטנות — לדור הבא.", "Full sets in small sizes — for the next generation."),
    basePriceIls: 160,
    sizeChartId: "kids",
    image: "/demo/cat-kids.webp",
    sortOrder: 8,
  },
];

/* ── Patches (spec §10) ───────────────────────────────────────────────────── */
export const demoPatches: PatchDef[] = [
  { id: "league-patch", name: L("شارة الدوري", "פאץ' ליגה", "League Patch"), priceIls: 5, active: true },
  { id: "cup-patch", name: L("شارة الكأس", "פאץ' גביע", "Cup Patch"), priceIls: 5, active: true },
  { id: "champions-patch", name: L("شارة الأبطال", "פאץ' אלופות", "Champions Patch"), priceIls: 5, active: true },
];

/* ── Size charts (placeholder measurements — spec §11) ────────────────────── */
const NOTE = L(
  "قياسات أولية للعرض فقط — سيتم تأكيد الجداول النهائية قبل الإطلاق. المقاسات قد تختلف بين أنواع المنتجات.",
  "מידות ראשוניות לתצוגה בלבד — הטבלאות הסופיות יאושרו לפני ההשקה. המידות עשויות להשתנות בין סוגי מוצרים.",
  "Preliminary measurements for display only — final charts will be confirmed before launch. Sizing may vary between product types.",
);

function chart(id: string, name: ReturnType<typeof L>, rows: [string, number, number][]): SizeChart {
  return { id, name, note: NOTE, rows: rows.map(([size, chestCm, lengthCm]) => ({ size, chestCm, lengthCm })), isPlaceholder: true };
}

export const demoSizeCharts: SizeChart[] = [
  chart("fan", L("نسخة المشجع", "גרסת אוהד", "Fan version"), [["S", 104, 69], ["M", 110, 71], ["L", 116, 73], ["XL", 122, 75], ["2XL", 128, 77]]),
  chart("player", L("نسخة اللاعب (قصّة ضيقة)", "גרסת שחקן (גזרה צמודה)", "Player version (athletic cut)"), [["S", 96, 68], ["M", 102, 70], ["L", 108, 72], ["XL", 114, 74], ["2XL", 120, 76]]),
  chart("retro", L("ريترو", "רטרו", "Retro"), [["S", 106, 70], ["M", 112, 72], ["L", 118, 74], ["XL", 124, 76], ["2XL", 130, 78]]),
  chart("long-sleeve", L("أكمام طويلة", "שרוול ארוך", "Long sleeve"), [["S", 104, 69], ["M", 110, 71], ["L", 116, 73], ["XL", 122, 75], ["2XL", 128, 77]]),
  chart("hoodie", L("هودي", "הודי", "Hoodie"), [["S", 112, 68], ["M", 118, 70], ["L", 124, 72], ["XL", 130, 74], ["2XL", 136, 76]]),
  chart("kids", L("أطفال", "ילדים", "Kids"), [["16", 66, 46], ["18", 70, 49], ["20", 74, 52], ["22", 78, 55], ["24", 82, 58], ["26", 86, 61], ["28", 90, 64]]),
];

/* ── Shipping zones (placeholder pricing within the ₪35–55 band, §12) ─────── */
export const demoZones: ShippingZone[] = [
  { id: "center", name: L("المركز (تل أبيب والمنطقة)", "מרכז (תל אביב והסביבה)", "Center (Tel Aviv area)"), priceIls: 35, etaDays: "2-4", active: true },
  { id: "sharon", name: L("الشارون", "השרון", "Sharon"), priceIls: 40, etaDays: "2-4", active: true },
  { id: "jerusalem", name: L("القدس والمنطقة", "ירושלים והסביבה", "Jerusalem area"), priceIls: 40, etaDays: "3-5", active: true },
  { id: "north", name: L("الشمال", "צפון", "North"), priceIls: 45, etaDays: "3-6", active: true },
  { id: "south", name: L("الجنوب", "דרום", "South"), priceIls: 45, etaDays: "3-6", active: true },
];

/* ── Products ─────────────────────────────────────────────────────────────── */
interface P {
  slug: string;
  cat: string;
  name: ReturnType<typeof L>;
  desc: ReturnType<typeof L>;
  price: number;
  versions?: Product["versions"];
  sleeves?: Product["sleeves"];
  lsAdj?: number;
  sizes?: string[];
  personal?: boolean;
  era?: string;
  season?: string;
  national?: boolean;
  kids?: boolean;
  featured?: boolean;
  status?: Product["status"];
  tags?: string[];
  related?: string[];
}

const DETAILS = L(
  "خامة بوليستر تسمح بالتهوية • خياطة نظيفة • مصنوع حسب الطلب • يُنصح بالغسيل البارد وعدم التجفيف الحراري.",
  "בד פוליאסטר נושם • תפירה נקייה • מיוצר לפי הזמנה • מומלץ כביסה קרה וללא מייבש.",
  "Breathable polyester fabric • clean stitching • made to order • cold wash recommended, no tumble dry.",
);

function product(p: P, i: number): Product {
  const name = {
    ar: `عرض تجريبي — ${p.name.ar}`,
    he: `דמו — ${p.name.he}`,
    en: `Demo — ${p.name.en}`,
  };
  return {
    id: `demo-${p.slug}`,
    slug: p.slug,
    categorySlug: p.cat,
    name,
    description: p.desc,
    details: DETAILS,
    seoTitle: name,
    seoDescription: p.desc,
    status: p.status ?? "made_to_order",
    basePriceIls: p.price,
    versions: p.versions ?? [],
    sleeves: p.sleeves ?? ["short"],
    longSleeveAdjustmentIls: p.lsAdj ?? 0,
    sizes: p.sizes ?? ADULT_SIZES,
    personalizable: p.personal ?? true,
    patchIds: p.personal === false ? [] : ["league-patch", "cup-patch", "champions-patch"],
    era: p.era,
    season: p.season,
    nationalTeam: p.national ?? false,
    kids: p.kids ?? false,
    qualifiesForFreeDelivery: true,
    featured: p.featured ?? false,
    images: [
      { src: `/demo/p-${p.slug}.webp`, alt: name },
      { src: `/demo/p-${p.slug}-b.webp`, alt: { ar: `${name.ar} — تفاصيل`, he: `${name.he} — פרטים`, en: `${name.en} — detail` } },
    ],
    relatedSlugs: p.related ?? [],
    tags: p.tags ?? [],
    rightsStatus: "cleared",
    isDemo: true,
    createdAt: new Date(2026, 5, 1 + i).toISOString(),
  };
}

export const demoProducts: Product[] = [
  product({
    slug: "crimson-2005",
    cat: "retro",
    name: L("قميص القرمزي، حقبة 2005", "החולצה הארגמנית, עידן 2005", "Crimson Home, 2005 Era"),
    desc: L("ليالي دوري الأبطال بنسختها الأصدق — قصّة ريترو وياقة كلاسيكية.", "לילות ליגת האלופות בגרסה הכי אמיתית — גזרת רטרו וצווארון קלאסי.", "Champions-nights energy in its truest form — retro cut, classic collar."),
    price: 170,
    era: "2000s",
    featured: true,
    related: ["royal-1998", "amber-2001", "midnight-longsleeve"],
  }, 0),
  product({
    slug: "royal-1998",
    cat: "retro",
    name: L("الأزرق الملكي، حقبة 1998", "הכחול המלכותי, עידן 1998", "Royal Away, 1998 Era"),
    desc: L("صيفُ مونديالٍ لا يُنسى — أزرق عميق وتطريز بارز.", "קיץ מונדיאל בלתי נשכח — כחול עמוק ורקמה בולטת.", "An unforgettable World-Cup summer — deep royal blue, raised embroidery."),
    price: 170,
    era: "1990s",
    featured: true,
    related: ["crimson-2005", "emerald-2007"],
  }, 1),
  product({
    slug: "emerald-2007",
    cat: "retro",
    name: L("الزمردي، حقبة 2007", "האמרלד, עידן 2007", "Emerald Third, 2007 Era"),
    desc: L("طقم ثالث نادر — أخضر زمردي بلمسات ذهبية.", "מדים שלישיים נדירים — ירוק אמרלד עם נגיעות זהב.", "A rare third kit — emerald green with gold accents."),
    price: 170,
    era: "2000s",
    related: ["crimson-2005", "royal-1998"],
  }, 2),
  product({
    slug: "amber-2001",
    cat: "retro",
    name: L("الكهرماني، حقبة 2001", "הענברי, עידן 2001", "Amber Classic, 2001 Era"),
    desc: L("برتقالي كهرماني جريء من مطلع الألفية.", "כתום ענברי נועז מתחילת שנות ה־2000.", "Bold amber orange from the turn of the millennium."),
    price: 170,
    era: "2000s",
    related: ["crimson-2005"],
  }, 3),
  product({
    slug: "onyx-home",
    cat: "current-season",
    name: L("أونيكس الأساسي 25/26", "אוניקס בית 25/26", "Onyx Home 25/26"),
    desc: L("أسود عميق بخطوط ذهبية — طقم هذا الموسم الأساسي.", "שחור עמוק עם פסי זהב — מדי הבית של העונה.", "Deep black with gold pinstripes — this season's home kit."),
    price: 140,
    versions: [
      { version: "fan", adjustmentIls: 0 },
      { version: "player", adjustmentIls: 20 },
    ],
    season: "25/26",
    featured: true,
    related: ["ivory-away", "graphite-player"],
  }, 4),
  product({
    slug: "ivory-away",
    cat: "current-season",
    name: L("العاجي الاحتياطي 25/26", "השנהב חוץ 25/26", "Ivory Away 25/26"),
    desc: L("أبيض عاجي نظيف بتفاصيل رمادية — طقم خارج الأرض.", "לבן שנהב נקי עם פרטים אפורים — מדי החוץ.", "Clean ivory white with slate details — the away kit."),
    price: 140,
    versions: [
      { version: "fan", adjustmentIls: 0 },
      { version: "player", adjustmentIls: 20 },
    ],
    season: "25/26",
    related: ["onyx-home"],
  }, 5),
  product({
    slug: "azure-national",
    cat: "national-teams",
    name: L("الأزرق السماوي — منتخب", "התכלת — נבחרת", "Azure National Home"),
    desc: L("سماويّ البطولات — قميص منتخب بروح الصيف الكبير.", "תכלת של טורנירים — חולצת נבחרת עם רוח הקיץ הגדול.", "Tournament azure — a national shirt with big-summer spirit."),
    price: 140,
    versions: [
      { version: "fan", adjustmentIls: 0 },
      { version: "player", adjustmentIls: 20 },
    ],
    national: true,
    featured: true,
    related: ["scarlet-national"],
  }, 6),
  product({
    slug: "scarlet-national",
    cat: "national-teams",
    name: L("القرمزي — منتخب، احتياطي", "השני — נבחרת, חוץ", "Scarlet National Away"),
    desc: L("أحمر قانٍ بقصّة حديثة — للمدرجات وللشارع.", "אדום עז בגזרה מודרנית — ליציע ולרחוב.", "Vivid scarlet in a modern cut — for the stands and the street."),
    price: 140,
    versions: [{ version: "fan", adjustmentIls: 0 }],
    national: true,
    related: ["azure-national"],
  }, 7),
  product({
    slug: "graphite-player",
    cat: "player-version",
    name: L("غرافيت — نسخة لاعب 24/25", "גרפיט — גרסת שחקן 24/25", "Graphite Player Edition 24/25"),
    desc: L("خامة المباريات الفعلية — خفيفة، ضيقة، بتقنية تهوية كاملة.", "בד המשחקים האמיתי — קל, צמוד, עם אוורור מלא.", "True match fabric — light, fitted, fully ventilated."),
    price: 160,
    versions: [{ version: "player", adjustmentIls: 0 }],
    season: "24/25",
    related: ["onyx-home"],
  }, 8),
  product({
    slug: "classic-white-fan",
    cat: "fan-version",
    name: L("الأبيض الكلاسيكي — نسخة مشجع", "הלבן הקלאסי — גרסת אוהד", "Classic White Fan 24/25"),
    desc: L("الأساسي الذي لا يخطئ — أبيض كلاسيكي بقصّة مريحة.", "הבסיס שלא מפספס — לבן קלאסי בגזרה נוחה.", "The essential that never misses — classic white, comfortable cut."),
    price: 140,
    versions: [{ version: "fan", adjustmentIls: 0 }],
    season: "24/25",
    related: ["ivory-away"],
  }, 9),
  product({
    slug: "midnight-longsleeve",
    cat: "long-sleeve",
    name: L("منتصف الليل — أكمام طويلة، حقبة 2003", "חצות — שרוול ארוך, עידן 2003", "Midnight Long Sleeve, 2003 Era"),
    desc: L("لياليّ الشتاء الأوروبية — كحلي منتصف الليل بأكمام كاملة.", "לילות חורף אירופיים — כחול חצות עם שרוול מלא.", "European winter nights — midnight navy with full sleeves."),
    price: 175,
    sleeves: ["long"],
    era: "2000s",
    related: ["crimson-2005"],
  }, 10),
  product({
    slug: "stealth-hoodie",
    cat: "hoodies",
    name: L("هودي ستيلث", "הודי סטלת'", "Stealth Football Hoodie"),
    desc: L("أسود مطفي بشعار مطرز — طبقة الشارع الأساسية.", "שחור מט עם רקמה — שכבת הרחוב הבסיסית.", "Matte black with embroidered crest — the essential street layer."),
    price: 250,
    personal: false,
    related: ["cream-hoodie"],
  }, 11),
  product({
    slug: "cream-hoodie",
    cat: "hoodies",
    name: L("هودي كريمي", "הודי קרם", "Cream Terrace Hoodie"),
    desc: L("كريمي دافئ بتطريز ذهبي — أناقة المدرجات.", "קרם חם עם רקמת זהב — אלגנטיות היציע.", "Warm cream with gold embroidery — terrace elegance."),
    price: 250,
    personal: false,
    related: ["stealth-hoodie"],
  }, 12),
  product({
    slug: "sunrise-kids",
    cat: "kids",
    name: L("طقم الشروق — أطفال", "סט זריחה — ילדים", "Sunrise Kids' Set"),
    desc: L("طقم كامل (قميص وشورت) بألوان الشروق — للمشجع الصغير.", "סט מלא (חולצה ומכנסיים) בצבעי זריחה — לאוהד הקטן.", "Full set (shirt + shorts) in sunrise colors — for the young fan."),
    price: 160,
    sizes: KIDS_SIZES,
    kids: true,
    versions: [{ version: "kids", adjustmentIls: 0 }],
    related: ["cobalt-kids"],
  }, 13),
  product({
    slug: "cobalt-kids",
    cat: "kids",
    name: L("طقم الكوبالت — أطفال", "סט קובלט — ילדים", "Cobalt Kids' Set"),
    desc: L("أزرق كوبالت بلمسة بيضاء — جاهز لأول مباراة.", "כחול קובלט עם נגיעה לבנה — מוכן למשחק הראשון.", "Cobalt blue with a white accent — ready for the first match."),
    price: 160,
    sizes: KIDS_SIZES,
    kids: true,
    versions: [{ version: "kids", adjustmentIls: 0 }],
    related: ["sunrise-kids"],
  }, 14),
  product({
    slug: "obsidian-2004",
    cat: "retro",
    name: L("الأسود الحجري، حقبة 2004", "האובסידיאן, עידן 2004", "Obsidian Keeper, 2004 Era"),
    desc: L("قميص حارس أسطوري — أسود كامل بتفاصيل فضية.", "חולצת שוער אגדית — שחור מלא עם פרטי כסף.", "A legendary keeper shirt — full black with silver detail."),
    price: 170,
    era: "2000s",
    status: "unavailable",
    related: ["crimson-2005"],
  }, 15),
];

/* ── Reviews (labeled demo — never production data, spec §22/§36) ─────────── */
export const demoReviews: Review[] = [
  { id: "rv1", productSlug: "crimson-2005", rating: 5, title: "جودة ممتازة", body: "الخامة والتطريز أفضل من المتوقع. وصل خلال ١٢ يوم.", displayName: "أحمد م.", locale: "ar", createdAt: "2026-06-20T10:00:00Z", status: "approved", verified: true, isDemo: true, photo: "/demo/rev-1.webp" },
  { id: "rv2", productSlug: "onyx-home", rating: 5, title: "מעולה", body: "הגזרה מדויקת וההדפסה של השם יצאה מושלמת.", displayName: "יואב ל.", locale: "he", createdAt: "2026-06-18T14:30:00Z", status: "approved", verified: true, isDemo: true },
  { id: "rv3", productSlug: "royal-1998", rating: 4, title: "Great retro feel", body: "Feels genuinely retro. Sizing runs slightly large — check the chart.", displayName: "Daniel K.", locale: "en", createdAt: "2026-06-15T09:12:00Z", status: "approved", verified: true, isDemo: true },
  { id: "rv4", productSlug: "azure-national", rating: 5, title: "هدية مثالية", body: "طلبته باسم ورقم — التغليف فخم والقميص أصلي الملمس.", displayName: "ليان ح.", locale: "ar", createdAt: "2026-06-10T19:45:00Z", status: "approved", verified: false, isDemo: true, photo: "/demo/rev-2.webp" },
  { id: "rv5", productSlug: "stealth-hoodie", rating: 5, title: "איכות של מותג", body: "ההודי חם, כבד ונראה יקר. שווה כל שקל.", displayName: "מאיה ב.", locale: "he", createdAt: "2026-06-05T08:00:00Z", status: "approved", verified: true, isDemo: true },
  { id: "rv6", productSlug: "graphite-player", rating: 4, title: "Player fit is real", body: "Tight athletic cut exactly like a match shirt. Order one size up for a relaxed fit.", displayName: "Sami A.", locale: "en", createdAt: "2026-06-01T12:00:00Z", status: "pending", verified: false, isDemo: true },
];

/* ── Customers ────────────────────────────────────────────────────────────── */
export const demoCustomers: Customer[] = [
  { id: "cust-demo", email: "demo@crowned.example", name: "Demo Customer", phone: "0500000000", role: "customer", createdAt: "2026-05-01T00:00:00Z", isDemo: true },
  { id: "admin-demo", email: "admin@crowned.example", name: "Demo Owner", role: "owner", createdAt: "2026-05-01T00:00:00Z", isDemo: true },
];

/** Demo-mode credentials (development only — see docs/admin-guide.md).
 * The demo login path is compiled out of production behavior: it only works
 * while demo mode is active. */
export const DEMO_CREDENTIALS = {
  customer: { email: "demo@crowned.example", password: "demo1234" },
  admin: { email: "admin@crowned.example", password: "admin1234" },
};

/* ── Orders ───────────────────────────────────────────────────────────────── */
export const demoOrders: Order[] = [
  {
    id: "ord-demo-1",
    orderNumber: "CR-DEMO01",
    createdAt: "2026-06-12T18:20:00Z",
    locale: "ar",
    customer: { name: "Demo Customer", email: "demo@crowned.example", phone: "0500000000", city: "حيفا", address: "شارع تجريبي 1", customerId: "cust-demo" },
    items: [
      { productId: "demo-crimson-2005", slug: "crimson-2005", title: demoProducts[0]!.name, image: "/demo/p-crimson-2005.webp", size: "L", personalization: { name: "AHMAD", number: "7" }, patchId: "champions-patch", patchName: demoPatches[2]!.name, unitPriceIls: 175, quantity: 1, lineTotalIls: 175 },
      { productId: "demo-royal-1998", slug: "royal-1998", title: demoProducts[1]!.name, image: "/demo/p-royal-1998.webp", size: "M", unitPriceIls: 170, quantity: 2, lineTotalIls: 340 },
    ],
    subtotalIls: 515,
    deliveryIls: 0,
    freeDelivery: true,
    totalIls: 515,
    zoneId: "north",
    paymentMethod: "bank_transfer",
    paymentStatus: "paid",
    fulfillmentStatus: "delivered",
    tracking: [
      { status: "order_received", at: "2026-06-12T18:20:00Z" },
      { status: "payment_confirmed", at: "2026-06-13T09:10:00Z" },
      { status: "sent_to_supplier", at: "2026-06-13T11:00:00Z" },
      { status: "production_started", at: "2026-06-14T08:00:00Z" },
      { status: "supplier_dispatched", at: "2026-06-17T15:30:00Z" },
      { status: "in_transit", at: "2026-06-18T10:00:00Z" },
      { status: "arrived_locally", at: "2026-06-26T12:00:00Z" },
      { status: "out_for_delivery", at: "2026-06-28T08:30:00Z" },
      { status: "delivered", at: "2026-06-28T14:45:00Z" },
    ],
    supplierReference: "SUP-88412",
    trackingNumber: "IL-DEMO-556677",
    sheetsSync: { status: "disabled" },
    isDemo: true,
  },
  {
    id: "ord-demo-2",
    orderNumber: "CR-DEMO02",
    createdAt: "2026-07-02T20:05:00Z",
    locale: "he",
    customer: { name: "Demo Customer", email: "demo@crowned.example", phone: "0500000000", city: "תל אביב", address: "רחוב דמו 2", customerId: "cust-demo" },
    items: [
      { productId: "demo-onyx-home", slug: "onyx-home", title: demoProducts[4]!.name, image: "/demo/p-onyx-home.webp", version: "player", size: "M", unitPriceIls: 160, quantity: 1, lineTotalIls: 160 },
    ],
    subtotalIls: 160,
    deliveryIls: 35,
    freeDelivery: false,
    totalIls: 195,
    zoneId: "center",
    paymentMethod: "bank_transfer",
    paymentStatus: "paid",
    fulfillmentStatus: "in_transit",
    tracking: [
      { status: "order_received", at: "2026-07-02T20:05:00Z" },
      { status: "payment_confirmed", at: "2026-07-03T10:00:00Z" },
      { status: "sent_to_supplier", at: "2026-07-03T12:00:00Z" },
      { status: "production_started", at: "2026-07-04T09:00:00Z" },
      { status: "supplier_dispatched", at: "2026-07-08T16:00:00Z" },
      { status: "in_transit", at: "2026-07-09T08:00:00Z" },
    ],
    supplierReference: "SUP-90233",
    trackingNumber: "IL-DEMO-778899",
    estimatedDeliveryAt: "2026-07-20T00:00:00Z",
    sheetsSync: { status: "disabled" },
    isDemo: true,
  },
  {
    id: "ord-demo-3",
    orderNumber: "CR-DEMO03",
    createdAt: "2026-07-11T13:40:00Z",
    locale: "en",
    customer: { name: "Demo Customer", email: "demo@crowned.example", phone: "0500000000", city: "Jerusalem", address: "Demo st. 3", customerId: "cust-demo" },
    items: [
      { productId: "demo-azure-national", slug: "azure-national", title: demoProducts[6]!.name, image: "/demo/p-azure-national.webp", version: "fan", size: "XL", personalization: { name: "LEO", number: "10" }, unitPriceIls: 140, quantity: 1, lineTotalIls: 140 },
    ],
    subtotalIls: 140,
    deliveryIls: 40,
    freeDelivery: false,
    totalIls: 180,
    zoneId: "jerusalem",
    paymentMethod: "bank_transfer",
    paymentStatus: "awaiting_payment",
    fulfillmentStatus: "awaiting_payment",
    tracking: [
      { status: "order_received", at: "2026-07-11T13:40:00Z" },
      { status: "awaiting_payment", at: "2026-07-11T13:40:05Z" },
    ],
    sheetsSync: { status: "disabled" },
    isDemo: true,
  },
];

/* ── Store settings ───────────────────────────────────────────────────────── */
export const demoSettings: StoreSettings = {
  announcement: L("توصيل مجاني عند طلب ٣ قطع أو أكثر", "משלוח חינם בהזמנת 3 פריטים ומעלה", "Free delivery on 3+ items"),
  whatsappNumber: "972500000000",
  instagramUsername: "crowned.demo",
  freeDeliveryMinItems: 3,
  supplierEtaText: L("التوصيل خلال ١٠–١٤ يومًا تقريبًا من لحظة شحن المورّد", "משלוח כ־10–14 ימים ממועד שילוח הספק", "Delivery in ~10–14 days from supplier dispatch"),
  bankTransferInstructions: L(
    "تفاصيل الحساب البنكي ستُرسل إليك برسالة تأكيد الطلب. يُشحن الطلب بعد التحقق من الدفع. (نص مبدئي — بانتظار تفاصيل الحساب الفعلية)",
    "פרטי חשבון הבנק יישלחו אליך בהודעת אישור ההזמנה. ההזמנה נשלחת לאחר אימות התשלום. (טקסט זמני — בהמתנה לפרטי החשבון)",
    "Bank account details will be sent in your order confirmation. Your order proceeds after payment verification. (Placeholder — awaiting real account details)",
  ),
  internationalMode: "waitlist",
  internationalNote: L(
    "الشحن الدولي قريبًا — تواصل معنا عبر واتساب للانضمام لقائمة الانتظار.",
    "משלוח בינלאומי בקרוב — כתבו לנו בוואטסאפ להצטרפות לרשימת ההמתנה.",
    "International delivery coming soon — message us on WhatsApp to join the waiting list.",
  ),
  paymentMethods: [
    { id: "bank_transfer", enabled: true, testMode: false, configured: true, label: L("تحويل بنكي", "העברה בנקאית", "Bank transfer") },
    { id: "card", enabled: false, testMode: true, configured: false, label: L("بطاقة ائتمان", "כרטיס אשראי", "Credit card") },
    { id: "bit", enabled: false, testMode: true, configured: false, label: L("Bit", "Bit", "Bit") },
    { id: "paybox", enabled: false, testMode: true, configured: false, label: L("PayBox", "PayBox", "PayBox") },
    { id: "paypal", enabled: false, testMode: true, configured: false, label: L("PayPal", "PayPal", "PayPal") },
  ],
  nonAffiliationNote: L(
    "CROWNED متجر مستقل وغير تابع لأي نادٍ أو اتحاد أو لاعب أو مصنّع. المنتجات نسخ مستوحاة عالية الجودة وليست منتجات رسمية مرخّصة.",
    "CROWNED היא חנות עצמאית שאינה קשורה לאף מועדון, התאחדות, שחקן או יצרן. המוצרים הם רפליקות איכותיות בהשראה — לא מוצרים רשמיים מורשים.",
    "CROWNED is an independent store, not affiliated with any club, federation, player or manufacturer. Products are high-quality inspired replicas — not official licensed merchandise.",
  ),
  legalEntity: { name: "", registrationNumber: "", taxNote: "" },
  policies: {
    returns: {
      title: L("سياسة الإلغاء والإرجاع والاستبدال", "מדיניות ביטול, החזרה והחלפה", "Cancellation, Return & Exchange Policy"),
      body: L(
        "يمكن إلغاء الطلبات فقط قبل بدء الإنتاج. بعد بدء الإنتاج، لا يمكن الإلغاء عادةً.\n\nلأن منتجاتنا تُصنع حسب الطلب، لا نقبل عمومًا الإرجاع أو الاستبدال في الحالات التالية:\n• اختيار مقاس غير صحيح من قبل العميل.\n• تغيير الرأي بعد بدء الإنتاج.\n• المنتجات المخصصة، بما يشمل الاسم أو الرقم أو الشارات أو أي تخصيص آخر.\n\nإذا وصل طلبك تالفًا أو معيبًا أو غير صحيح، يرجى التواصل معنا خلال 48 ساعة من الاستلام مع صور واضحة. سنراجع المشكلة وسنوفر بديلًا أو حلًا مناسبًا آخر عند الاقتضاء.\n\nيرجى استخدام جدول المقاسات قبل الطلب للتأكد من اختيار المقاس الصحيح.",
        "ניתן לבטל הזמנות רק לפני תחילת הייצור. לאחר תחילת הייצור, ביטול אינו אפשרי בדרך כלל.\n\nמכיוון שהמוצרים שלנו מיוצרים לפי הזמנה, אנו בדרך כלל לא מקבלים החזרות או החלפות עבור:\n• מידה שגויה שנבחרה על ידי הלקוח.\n• שינוי דעה לאחר תחילת הייצור.\n• מוצרים בהתאמה אישית, כולל שם, מספר, פאצ'ים או כל התאמה אחרת.\n\nאם ההזמנה הגיעה פגומה, לקויה או שגויה, אנא צרו קשר תוך 48 שעות מהמסירה עם תמונות ברורות. נבחן את הפנייה ובמקרים המתאימים נספק החלפה או פתרון הולם אחר.\n\nאנא השתמשו בטבלת המידות לפני ההזמנה כדי לוודא בחירת מידה נכונה.",
        "Orders may be cancelled only before production has started. Once production has begun, cancellation is generally not possible.\n\nBecause our products are made to order, we generally do not accept returns or exchanges for:\n• Incorrect size selected by the customer.\n• Change of mind after production has started.\n• Customized products, including a name, number, patches, or other personalization.\n\nIf your order arrives damaged, defective, or incorrect, please contact us within 48 hours of delivery with clear photos. We will review the issue and, where appropriate, provide a replacement or another suitable solution.\n\nPlease use the size chart before ordering to ensure you select the correct size.",
      ),
      needsLegalReview: true,
    },
    privacy: {
      title: L("سياسة الخصوصية", "מדיניות פרטיות", "Privacy Policy"),
      body: L(
        "[نص مبدئي — يتطلب صياغة ومراجعة قانونية قبل الإطلاق]\n\nنجمع بيانات الطلب (الاسم، الهاتف، البريد، العنوان) لمعالجة الطلبات وتحديثات التوصيل. لا نبيع بياناتك. تُخزن البيانات لدى مزوّدي خدمة موثوقين (قاعدة بيانات، مزوّد دفع، مزامنة طلبات). لا تُرسل بيانات شخصية إلى أدوات التحليلات.",
        "[טקסט זמני — נדרש ניסוח ואישור משפטי לפני השקה]\n\nאנו אוספים נתוני הזמנה (שם, טלפון, אימייל, כתובת) לצורך טיפול בהזמנות ועדכוני משלוח. איננו מוכרים את הנתונים שלך. הנתונים נשמרים אצל ספקי שירות אמינים (מסד נתונים, ספק תשלום, סנכרון הזמנות). מידע אישי אינו נשלח לכלי אנליטיקה.",
        "[Placeholder — requires drafting and legal review before launch]\n\nWe collect order data (name, phone, email, address) to process orders and delivery updates. We do not sell your data. Data is stored with trusted processors (database, payment provider, order sync). Personal information is never sent to analytics tools.",
      ),
      needsLegalReview: true,
    },
    terms: {
      title: L("الشروط والأحكام", "תנאי שימוש", "Terms & Conditions"),
      body: L(
        "[نص مبدئي — يتطلب صياغة ومراجعة قانونية قبل الإطلاق]\n\nباستخدامك للموقع وإتمام الطلب فأنت توافق على سياسات المتجر، بما فيها سياسة الإلغاء والإرجاع وسياسة الخصوصية. الأسعار بالشيكل وتشمل ما يُذكر صراحةً فقط.",
        "[טקסט זמני — נדרש ניסוח ואישור משפטי לפני השקה]\n\nהשימוש באתר וביצוע הזמנה מהווים הסכמה למדיניות החנות, כולל מדיניות הביטול וההחזרה ומדיניות הפרטיות. המחירים בשקלים וכוללים רק את המפורט במפורש.",
        "[Placeholder — requires drafting and legal review before launch]\n\nUsing this site and placing an order constitutes agreement to the store policies, including the cancellation/return policy and privacy policy. Prices are in ILS and include only what is explicitly stated.",
      ),
      needsLegalReview: true,
    },
    accessibility: {
      title: L("بيان إتاحة الوصول", "הצהרת נגישות", "Accessibility Statement"),
      body: L(
        "صُمم هذا المتجر وفق معايير WCAG 2.2 مستوى AA: تنقّل كامل بلوحة المفاتيح، تباين ألوان مناسب، دعم قارئات الشاشة، ودعم تقليل الحركة. نعمل باستمرار على تحسين الإتاحة — إذا واجهت صعوبة، راسلنا عبر صفحة التواصل وسنساعدك بسرعة.",
        "החנות תוכננה בהתאם להנחיות WCAG 2.2 רמה AA: ניווט מלא במקלדת, ניגודיות צבעים מתאימה, תמיכה בקוראי מסך ותמיכה בהפחתת אנימציה. אנו פועלים לשיפור מתמיד של הנגישות — אם נתקלת בקושי, פנו אלינו דרך עמוד יצירת הקשר ונסייע במהירות.",
        "This store is built to WCAG 2.2 level AA guidelines: full keyboard navigation, appropriate color contrast, screen-reader support and reduced-motion support. We continuously improve accessibility — if you encounter difficulty, contact us via the contact page and we will help promptly.",
      ),
      needsLegalReview: false,
    },
  },
};
