/**
 * Generates supabase/seed.sql from the canonical demo data in
 * src/services/demo/seed-data.ts, so local-dev Supabase and the in-browser
 * demo stay identical. DEVELOPMENT ONLY — never run the output in
 * production (see file header it emits).
 *
 * Run: node scripts/export-seed.mjs   (spawns itself with type stripping)
 */
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

if (!process.env.CROWNED_SEED_INNER) {
  const res = spawnSync(process.execPath, ["--experimental-strip-types", fileURLToPath(import.meta.url)], {
    stdio: "inherit",
    env: { ...process.env, CROWNED_SEED_INNER: "1" },
    cwd: root,
  });
  process.exit(res.status ?? 0);
}

const { writeFileSync } = await import("node:fs");
const seed = await import("../src/services/demo/seed-data.ts");

const q = (v) => `'${String(v).replaceAll("'", "''")}'`;
const j = (obj) => `${q(JSON.stringify(obj))}::jsonb`;

const lines = [
  "-- GENERATED by scripts/export-seed.mjs — do not edit by hand.",
  "-- DEVELOPMENT/STAGING ONLY. Never run against production: all rows are",
  "-- demo-labeled and demo reviews must never be publicly served as real.",
  "begin;",
];

for (const c of seed.demoCategories) lines.push(`insert into public.categories (id, data) values (${q(c.slug)}, ${j(c)});`);
for (const p of seed.demoPatches) lines.push(`insert into public.patches (id, active, data) values (${q(p.id)}, ${p.active}, ${j(p)});`);
for (const s of seed.demoSizeCharts) lines.push(`insert into public.size_charts (id, data) values (${q(s.id)}, ${j(s)});`);
for (const z of seed.demoZones) lines.push(`insert into public.shipping_zones (id, active, data) values (${q(z.id)}, ${z.active}, ${j(z)});`);
for (const p of seed.demoProducts) {
  lines.push(
    `insert into public.products (id, slug, status, rights_status, category_slug, data, created_at) values (${q(p.id)}, ${q(p.slug)}, ${q(p.status)}, ${q(p.rightsStatus)}, ${q(p.categorySlug)}, ${j(p)}, ${q(p.createdAt)});`,
  );
}
for (const r of seed.demoReviews) {
  lines.push(`insert into public.reviews (id, product_slug, status, data, created_at) values (${q(r.id)}, ${r.productSlug ? q(r.productSlug) : "null"}, ${q(r.status)}, ${j(r)}, ${q(r.createdAt)});`);
}
lines.push(`insert into public.store_settings (id, data) values ('main', ${j(seed.demoSettings)});`);
lines.push("commit;");
lines.push("");
lines.push("-- Demo ORDERS are intentionally not seeded into Postgres: orders carry");
lines.push("-- contact hashes created by the place-order function. Place a test order");
lines.push("-- through the storefront instead.");

writeFileSync(join(root, "supabase", "seed.sql"), lines.join("\n"));
console.log(`wrote supabase/seed.sql (${lines.length} lines)`);
