/** One-off: deep-merges the missing key set into the three dictionaries.
 * Kept in the repo for provenance; safe to re-run (idempotent). */
import { readFileSync, writeFileSync } from "node:fs";

const ADD = {
  en: {
    common: { breadcrumbs: "Breadcrumbs", demoBanner: "DEMO MODE — sample catalog and simulated checkout for preview only. No real orders, payments or messages.", demoFooterNote: "Running in demo mode — development data only.", demoLabel: "Demo", language: "Language", select: "Select…", signupThanks: "Thanks — you're on the list.", viewAll: "View all" },
    about: { intro: "CROWNED is a curated football-shirt destination — retro icons and current-season kits, selected with care and delivered across Israel.", body1: "We started from a simple idea: the shirts that defined eras deserve better than a crowded marketplace. Every piece in the catalog is chosen for its story — a season, a final, a colorway people remember.", body2: "Every order is prepared on demand: you choose the size, version and personalization, we handle production and keep you updated at every step until it reaches your door." },
    account: { confirmEmail: "Check your inbox to confirm your email, then log in.", demoHint: "Demo accounts for preview:", emailTaken: "An account with this email already exists.", invalidCredentials: "Incorrect email or password.", passwordHint: "At least 8 characters.", profileTab: "Profile", registerValidation: "Please fill a valid name, email and a password of 8+ characters." },
    cart: { deliveryAtCheckout: "Calculated at checkout" },
    checkout: { confirmations: "Confirmations", days: "days", demoPaymentNote: "Demo mode: checkout is simulated for preview. No real payment is processed and no money moves.", fixErrors: "Please fix the following:", free: "Free", manualVerification: "Verified manually", marketingConsent: "Keep me updated about new drops (optional).", noMethods: "No payment methods are currently available. Please contact us on WhatsApp.", policyAckRequired: "Please confirm the store policy to continue.", selectPayment: "Please choose a payment method.", selectZone: "Please choose a delivery area.", selectZoneShort: "Select area", simulatedDemo: "Simulated (demo)", zone: "Delivery area", error_generic: "Something went wrong placing the order. Please try again.", error_payment_method_unavailable: "This payment method is not available.", error_zone_unavailable: "The selected delivery area is not available.", error_empty_cart: "Your cart is empty.", error_product_unavailable: "A product in your cart is no longer available.", error_invalid_size: "A selected size is not available.", error_invalid_version: "A selected version is not available.", error_invalid_sleeve: "A selected sleeve option is not available.", error_invalid_patch: "A selected patch is not available.", error_invalid_quantity: "Invalid quantity.", error_personalization_unavailable: "Personalization is not available for a product in your cart.", error_invalid_personalization: "Invalid name or number." },
    confirmation: { bankNote: "Your order will move to preparation as soon as the transfer is verified (usually within one business day).", nextSteps: "We've received your order. You'll get updates as it moves through production, dispatch and delivery — and you can check its status any time." },
    contact: { intro: "Questions about an order, sizing or a specific shirt? The fastest way to reach us is WhatsApp — or leave a message here.", message: "Message", received: "Message received — we'll get back to you soon.", send: "Send", validation: "Please fill your name, a valid contact and a message." },
    delivery: { eta: "Local ETA", etaClarification: "the 10–14 day estimate starts when the supplier dispatches, not at checkout.", internationalTitle: "International delivery", intro: "We deliver across Israel through configurable delivery areas. Delivery is free from 3 qualifying items.", joinWaitlist: "Join the waiting list", zone: "Area", zonesTitle: "Delivery areas" },
    errors: { confirmSize: "Please confirm you checked the size chart.", confirmSpelling: "Please confirm the spelling of your personalization.", invalidName: "Name: letters only, up to 14 characters.", invalidNumber: "Number: 1–2 digits." },
    faq: { intro: "Quick answers about ordering, sizing, delivery and returns.", q1: "How long does delivery take?", a1: "Orders are made to order. After the supplier dispatches, delivery takes roughly 10–14 days, plus local delivery time in your area.", q2: "How do I unlock free delivery?", a2: "Add 3 or more qualifying items to your order — it's based on the number of items, not the total.", q3: "Is the name and number really free?", a3: "Yes. Name and number personalization is free; an optional patch adds ₪5.", q4: "Which size should I take?", a4: "Check the size guide on every product page — charts differ between fan, player, retro, long-sleeve, hoodie and kids items. Player versions run slim.", q5: "Can I cancel or return my order?", a5: "Orders can be cancelled only before production starts. Because items are made to order, returns are generally not accepted for size mistakes or change of mind — see the full policy.", q6: "What if my order arrives damaged or wrong?", a6: "Contact us within 48 hours of delivery with clear photos and we'll review it and provide a replacement or another suitable solution where appropriate.", q7: "How do I pay?", a7: "Currently by bank transfer (verified manually before production). More payment methods are coming.", q8: "How do I track my order?", a8: "Use the Track Order page with your order number plus the email or phone used at checkout." },
    filters: { adults: "Adults", audience: "For", between150200: "₪150–₪200", clear: "Clear filters", era: "Era", more: "More", over200: "Over ₪200", personalizable: "Personalization available", price: "Price", sort: "Sort", sortFeatured: "Featured", sortNewest: "Newest", sortPriceAsc: "Price: low to high", sortPriceDesc: "Price: high to low", title: "Filters", under150: "Under ₪150" },
    footer: { accessibility: "Accessibility statement", delivery: "Delivery", faq: "FAQ", howOrdering: "How ordering works", privacy: "Privacy policy", returnsPolicy: "Cancellation & returns", terms: "Terms & conditions" },
    home: { fanCardTitle: "Everyday comfort", fanPoint1: "Regular, relaxed cut", fanPoint2: "Softer everyday fabric", fanPoint3: "The classic choice for the stands", playerCardTitle: "Built like match day", playerPoint1: "Slim athletic cut", playerPoint2: "Lightweight ventilated match fabric", playerPoint3: "Details as worn on the pitch", personalizationDetail: "Your name and number are printed free on any personalizable shirt. Add an official-style patch for ₪5.", trustDeliveryTitle: "Delivery across Israel", trustDeliveryBody: "~10–14 days from supplier dispatch", trustQualityTitle: "Finished properly", trustQualityBody: "High-end replica quality, checked before dispatch", trustSupportTitle: "Real support", trustSupportBody: "WhatsApp us about sizing, orders or anything else", step1Title: "Pick your shirt", step1Body: "Size, version, sleeve — and free name & number.", step2Title: "Confirm your order", step2Body: "Pay online or reserve with bank transfer.", step3Title: "We produce it", step3Body: "Your piece is made to order and quality-checked.", step4Title: "Delivered to you", step4Body: "~10–14 days from dispatch, tracked the whole way." },
    how: { intro: "Every CROWNED piece is made to order. Here is exactly what happens after you order — no surprises.", etaNote: "The 10–14 day estimate begins when the supplier dispatches your order — not at checkout. You can follow every stage on the tracking page.", step1Title: "Order received", step1Body: "Your order and personalization are recorded exactly as entered.", step2Title: "Payment confirmed", step2Body: "Online payments confirm automatically; bank transfers are verified manually.", step3Title: "Sent to supplier", step3Body: "Your order is prepared and passed to production.", step4Title: "Production", step4Body: "The shirt is produced with your size, version and printing.", step5Title: "Supplier dispatch", step5Body: "Your order leaves production — the 10–14 day window starts here.", step6Title: "In transit", step6Body: "On its way to Israel.", step7Title: "Local delivery", step7Body: "Arrived locally and out for delivery in your area.", step8Title: "Delivered", step8Body: "Enjoy it. Tag us — we love seeing shirts in the wild." },
    issues: { category: "Issue type", contact: "Email or phone", description: "What happened?", intro: "If your order arrived damaged, defective or incorrect, tell us within 48 hours of delivery with clear photos and we'll make it right where appropriate.", photo: "Photos", photoHint: "Clear photos help us resolve this faster.", received: "Report received — we'll review it and get back to you.", resolution: "Requested resolution", resolutionHint: "e.g. replacement", submit: "Send report", validation: "Please fill your name, contact and a description (10+ characters).", cat_damaged: "Damaged product", cat_defective: "Defective product", cat_incorrect_item: "Incorrect item", cat_incorrect_size_supplied: "Incorrect size supplied", cat_incorrect_personalization: "Incorrect personalization", cat_missing_item: "Missing item", cat_delivery_problem: "Delivery problem", cat_other: "Other" },
    policy: { legalReviewNote: "Draft — pending professional legal review before launch." },
    product: { careBody: "Cold machine wash inside out. No tumble dry, no iron directly on prints or badges.", freeLabel: "Free", galleryThumbs: "Product images", patchNone: "No patch", priceUpdatesNote: "Price updates with your choices", zoomImage: "Zoom image", versionKids: "Kids", versionRetro: "Retro" },
    reviews: { displayName: "Display name", moderationNote: "Reviews are published after moderation. Please avoid personal details.", pageIntro: "Real feedback from CROWNED customers. Demo entries are labeled and exist only in the preview build.", photoAlt: "Photo from {name}", photoInvalid: "Photo must be JPG/PNG/WebP up to 4MB.", photoLabel: "Add a photo (optional)", reviewTitle: "Title" },
    search: { hint: "Search by team, era, season, type — e.g. “retro 2005” or “hoodie”.", placeholder: "Search shirts…", resultsFor: "{count} result(s) for “{query}”", tryThese: "No exact matches — maybe one of these:" },
    shop: { metaDescription: "The full CROWNED catalog — retro icons, current-season kits, national teams, hoodies and kids' sets.", noResults: "Nothing matches those filters", noResultsBody: "Try clearing a filter or two — or search for something else.", resultCount: "{count} item(s)" },
    sizeGuide: { chest: "Chest (flat)", length: "Length", placeholderNote: "Preliminary chart — final measurements will be confirmed before launch.", variesNote: "Sizing varies between product types — always check the chart for the specific item." },
    tracking: { carrierLink: "Carrier tracking", estimatedDelivery: "Estimated delivery", intro: "Enter your order number together with the email or phone used at checkout.", items: "item(s)", metaDescription: "Track your CROWNED order securely with your order number and contact details.", reportIssue: "Report a problem with this order", timeline: "Order progress", trackingNumber: "Tracking number", verifyHint: "The email or phone used when ordering" },
    wishlist: { emptyBody: "Tap the heart on any product to keep it here.", emptyTitle: "Your wishlist is empty" },
  },
  ar: {
    common: { breadcrumbs: "مسار التنقل", demoBanner: "وضع تجريبي — كتالوج تجريبي ودفع محاكى للمعاينة فقط. لا طلبات أو مدفوعات أو رسائل حقيقية.", demoFooterNote: "يعمل بالوضع التجريبي — بيانات تطوير فقط.", demoLabel: "تجريبي", language: "اللغة", select: "اختر…", signupThanks: "شكرًا — تمت إضافتك للقائمة.", viewAll: "عرض الكل" },
    about: { intro: "CROWNED وجهة مختارة بعناية لقمصان كرة القدم — أيقونات ريترو وأطقم الموسم الحالي، تُنتقى بعناية وتُوصَّل في كل أنحاء البلاد.", body1: "بدأنا من فكرة بسيطة: القمصان التي صنعت حقبًا كاملة تستحق أفضل من سوق مزدحم. كل قطعة في الكتالوج مختارة لقصتها — موسم، نهائي، أو ألوان يتذكرها الناس.", body2: "كل طلب يُجهَّز حسب الطلب: تختار المقاس والنسخة والتخصيص، ونحن نتولى الإنتاج ونبقيك على اطلاع في كل مرحلة حتى يصل إلى بابك." },
    account: { confirmEmail: "تفقد بريدك لتأكيد الحساب ثم سجّل الدخول.", demoHint: "حسابات تجريبية للمعاينة:", emailTaken: "يوجد حساب بهذا البريد بالفعل.", invalidCredentials: "البريد أو كلمة المرور غير صحيحة.", passwordHint: "٨ أحرف على الأقل.", profileTab: "الملف الشخصي", registerValidation: "يرجى إدخال اسم صحيح وبريد صالح وكلمة مرور من ٨ أحرف أو أكثر." },
    cart: { deliveryAtCheckout: "يُحسب عند الدفع" },
    checkout: { confirmations: "تأكيدات", days: "أيام", demoPaymentNote: "وضع تجريبي: الدفع محاكى للمعاينة فقط. لا يتم أي دفع حقيقي ولا تتحرك أي أموال.", fixErrors: "يرجى تصحيح ما يلي:", free: "مجاني", manualVerification: "تحقق يدوي", marketingConsent: "أرغب بتلقي تحديثات عن الإصدارات الجديدة (اختياري).", noMethods: "لا توجد طرق دفع متاحة حاليًا. تواصل معنا عبر واتساب.", policyAckRequired: "يرجى تأكيد سياسة المتجر للمتابعة.", selectPayment: "يرجى اختيار طريقة الدفع.", selectZone: "يرجى اختيار منطقة التوصيل.", selectZoneShort: "اختر المنطقة", simulatedDemo: "محاكى (تجريبي)", zone: "منطقة التوصيل", error_generic: "حدث خطأ أثناء إتمام الطلب. حاول مجددًا.", error_payment_method_unavailable: "طريقة الدفع هذه غير متاحة.", error_zone_unavailable: "منطقة التوصيل المختارة غير متاحة.", error_empty_cart: "سلتك فارغة.", error_product_unavailable: "أحد المنتجات في سلتك لم يعد متاحًا.", error_invalid_size: "المقاس المختار غير متاح.", error_invalid_version: "النسخة المختارة غير متاحة.", error_invalid_sleeve: "خيار الأكمام غير متاح.", error_invalid_patch: "الشارة المختارة غير متاحة.", error_invalid_quantity: "كمية غير صالحة.", error_personalization_unavailable: "التخصيص غير متاح لأحد المنتجات.", error_invalid_personalization: "اسم أو رقم غير صالح." },
    confirmation: { bankNote: "سينتقل طلبك إلى التجهيز فور التحقق من التحويل (عادة خلال يوم عمل).", nextSteps: "استلمنا طلبك. ستصلك التحديثات مع تقدمه في الإنتاج والشحن والتوصيل — ويمكنك متابعة حالته في أي وقت." },
    contact: { intro: "سؤال عن طلب أو مقاس أو قميص معيّن؟ أسرع طريقة هي واتساب — أو اترك رسالة هنا.", message: "الرسالة", received: "وصلتنا رسالتك — سنعود إليك قريبًا.", send: "إرسال", validation: "يرجى إدخال الاسم ووسيلة تواصل صحيحة ورسالة." },
    delivery: { eta: "مدة التوصيل المحلي", etaClarification: "تقدير ١٠–١٤ يومًا يبدأ من لحظة شحن المورّد، وليس من إتمام الطلب.", internationalTitle: "الشحن الدولي", intro: "نوصّل في جميع أنحاء البلاد عبر مناطق توصيل قابلة للتخصيص. التوصيل مجاني عند طلب ٣ قطع مؤهلة أو أكثر.", joinWaitlist: "انضم لقائمة الانتظار", zone: "المنطقة", zonesTitle: "مناطق التوصيل" },
    errors: { confirmSize: "يرجى تأكيد مراجعتك لجدول المقاسات.", confirmSpelling: "يرجى تأكيد تهجئة التخصيص.", invalidName: "الاسم: أحرف فقط، حتى ١٤ حرفًا.", invalidNumber: "الرقم: خانة أو خانتان." },
    faq: { intro: "إجابات سريعة عن الطلب والمقاسات والتوصيل والإرجاع.", q1: "كم تستغرق مدة التوصيل؟", a1: "الطلبات تُصنع حسب الطلب. بعد شحن المورّد، يستغرق التوصيل ١٠–١٤ يومًا تقريبًا، إضافة إلى مدة التوصيل المحلي في منطقتك.", q2: "كيف أحصل على توصيل مجاني؟", a2: "أضف ٣ قطع مؤهلة أو أكثر لطلبك — الحساب بعدد القطع وليس بقيمة الطلب.", q3: "هل الاسم والرقم مجانيان فعلًا؟", a3: "نعم. تخصيص الاسم والرقم مجاني؛ الشارة الاختيارية تضيف ٥ شيكل.", q4: "أي مقاس أختار؟", a4: "راجع جدول المقاسات في كل صفحة منتج — الجداول تختلف بين نسخ المشجع واللاعب والريترو والأكمام الطويلة والهودي والأطفال. نسخة اللاعب ضيقة.", q5: "هل يمكن الإلغاء أو الإرجاع؟", a5: "يمكن الإلغاء فقط قبل بدء الإنتاج. لأن القطع تُصنع حسب الطلب، لا نقبل عمومًا الإرجاع بسبب خطأ في المقاس أو تغيير الرأي — راجع السياسة كاملة.", q6: "ماذا لو وصل الطلب تالفًا أو خاطئًا؟", a6: "تواصل معنا خلال ٤٨ ساعة من الاستلام مع صور واضحة وسنراجع الحالة ونوفر بديلًا أو حلًا مناسبًا عند الاقتضاء.", q7: "كيف أدفع؟", a7: "حاليًا بالتحويل البنكي (يُتحقق منه يدويًا قبل الإنتاج). طرق دفع إضافية قريبًا.", q8: "كيف أتتبع طلبي؟", a8: "من صفحة تتبع الطلب باستخدام رقم الطلب مع البريد أو الهاتف المستخدم عند الشراء." },
    filters: { adults: "كبار", audience: "الفئة", between150200: "₪150–₪200", clear: "مسح الفلاتر", era: "الحقبة", more: "المزيد", over200: "فوق ₪200", personalizable: "قابل للتخصيص", price: "السعر", sort: "الترتيب", sortFeatured: "مميز", sortNewest: "الأحدث", sortPriceAsc: "السعر: من الأقل", sortPriceDesc: "السعر: من الأعلى", title: "الفلاتر", under150: "أقل من ₪150" },
    footer: { accessibility: "بيان إتاحة الوصول", delivery: "التوصيل", faq: "الأسئلة الشائعة", howOrdering: "كيف يعمل الطلب", privacy: "سياسة الخصوصية", returnsPolicy: "الإلغاء والإرجاع", terms: "الشروط والأحكام" },
    home: { fanCardTitle: "راحة يومية", fanPoint1: "قصّة عادية مريحة", fanPoint2: "خامة أنعم للاستخدام اليومي", fanPoint3: "الخيار الكلاسيكي للمدرجات", playerCardTitle: "كأنك في المباراة", playerPoint1: "قصّة رياضية ضيقة", playerPoint2: "خامة مباريات خفيفة بتهوية كاملة", playerPoint3: "تفاصيل كما تُلبس في الملعب", personalizationDetail: "اسمك ورقمك يُطبعان مجانًا على أي قميص قابل للتخصيص. أضف شارة بطابع رسمي مقابل ٥ شيكل.", trustDeliveryTitle: "توصيل لكل البلاد", trustDeliveryBody: "١٠–١٤ يومًا تقريبًا من شحن المورّد", trustQualityTitle: "تشطيب حقيقي", trustQualityBody: "جودة نسخ عالية تُفحص قبل الشحن", trustSupportTitle: "دعم حقيقي", trustSupportBody: "راسلنا واتساب عن المقاسات والطلبات وأي شيء آخر", step1Title: "اختر قميصك", step1Body: "المقاس والنسخة والأكمام — مع اسم ورقم مجانًا.", step2Title: "أكّد طلبك", step2Body: "ادفع أونلاين أو احجز بتحويل بنكي.", step3Title: "نُنتجه لك", step3Body: "قطعتك تُصنع حسب الطلب وتُفحص جودتها.", step4Title: "يصلك حتى الباب", step4Body: "١٠–١٤ يومًا تقريبًا من الشحن، مع تتبع كامل." },
    how: { intro: "كل قطعة من CROWNED تُصنع حسب الطلب. إليك بالضبط ما يحدث بعد طلبك — دون مفاجآت.", etaNote: "تقدير ١٠–١٤ يومًا يبدأ عند شحن المورّد لطلبك — لا عند إتمام الشراء. يمكنك متابعة كل مرحلة في صفحة التتبع.", step1Title: "استلام الطلب", step1Body: "يُسجَّل طلبك وتخصيصك تمامًا كما أدخلتهما.", step2Title: "تأكيد الدفع", step2Body: "الدفع الإلكتروني يتأكد تلقائيًا؛ التحويل البنكي يُتحقق منه يدويًا.", step3Title: "الإرسال للمورّد", step3Body: "يُجهَّز طلبك ويُمرَّر إلى الإنتاج.", step4Title: "الإنتاج", step4Body: "يُنتج القميص بمقاسك ونسختك وطباعتك.", step5Title: "شحن المورّد", step5Body: "يغادر طلبك الإنتاج — من هنا تبدأ مدة الـ١٠–١٤ يومًا.", step6Title: "في الطريق", step6Body: "في طريقه إلى البلاد.", step7Title: "التوصيل المحلي", step7Body: "وصل محليًا وهو في طريقه إليك.", step8Title: "تم التسليم", step8Body: "استمتع به — وشاركنا صورة، نحب رؤية القمصان في الشارع." },
    issues: { category: "نوع المشكلة", contact: "بريد أو هاتف", description: "ماذا حدث؟", intro: "إذا وصل طلبك تالفًا أو معيبًا أو غير صحيح، أخبرنا خلال ٤٨ ساعة من الاستلام مع صور واضحة وسنصحح الأمر عند الاقتضاء.", photo: "صور", photoHint: "الصور الواضحة تساعدنا على الحل أسرع.", received: "وصلنا البلاغ — سنراجعه ونعود إليك.", resolution: "الحل المطلوب", resolutionHint: "مثلًا: استبدال", submit: "إرسال البلاغ", validation: "يرجى إدخال الاسم ووسيلة التواصل ووصف (١٠ أحرف على الأقل).", cat_damaged: "منتج تالف", cat_defective: "منتج معيب", cat_incorrect_item: "منتج خاطئ", cat_incorrect_size_supplied: "مقاس مورَّد خاطئ", cat_incorrect_personalization: "تخصيص خاطئ", cat_missing_item: "قطعة ناقصة", cat_delivery_problem: "مشكلة توصيل", cat_other: "أخرى" },
    policy: { legalReviewNote: "مسودة — بانتظار مراجعة قانونية مهنية قبل الإطلاق." },
    product: { careBody: "غسيل بارد مقلوبًا. لا مجفف حراري، ولا كيّ مباشر على الطباعة أو الشارات.", freeLabel: "مجاني", galleryThumbs: "صور المنتج", patchNone: "بدون شارة", priceUpdatesNote: "السعر يتحدّث مع اختياراتك", zoomImage: "تكبير الصورة", versionKids: "أطفال", versionRetro: "ريترو" },
    reviews: { displayName: "الاسم الظاهر", moderationNote: "تُنشر التقييمات بعد المراجعة. تجنّب التفاصيل الشخصية.", pageIntro: "آراء حقيقية من عملاء CROWNED. الإدخالات التجريبية معلَّمة وتظهر في نسخة المعاينة فقط.", photoAlt: "صورة من {name}", photoInvalid: "الصورة: JPG/PNG/WebP حتى 4MB.", photoLabel: "أضف صورة (اختياري)", reviewTitle: "العنوان" },
    search: { hint: "ابحث بالفريق أو الحقبة أو الموسم أو النوع — مثل «ريترو 2005» أو «هودي».", placeholder: "ابحث عن قميص…", resultsFor: "{count} نتيجة لـ «{query}»", tryThese: "لا نتائج مطابقة — ربما يعجبك أحد هذه:" },
    shop: { metaDescription: "كتالوج CROWNED الكامل — أيقونات ريترو وأطقم الموسم الحالي والمنتخبات والهوديز وأطقم الأطفال.", noResults: "لا شيء يطابق هذه الفلاتر", noResultsBody: "جرّب إزالة فلتر أو اثنين — أو ابحث عن شيء آخر.", resultCount: "{count} قطعة" },
    sizeGuide: { chest: "الصدر (مسطّح)", length: "الطول", placeholderNote: "جدول أولي — ستُؤكَّد القياسات النهائية قبل الإطلاق.", variesNote: "المقاسات تختلف بين أنواع المنتجات — راجع دائمًا جدول القطعة نفسها." },
    tracking: { carrierLink: "تتبع شركة الشحن", estimatedDelivery: "موعد التسليم المتوقع", intro: "أدخل رقم الطلب مع البريد الإلكتروني أو الهاتف المستخدم عند الشراء.", items: "قطعة", metaDescription: "تتبع طلبك من CROWNED بأمان برقم الطلب وبيانات التواصل.", reportIssue: "الإبلاغ عن مشكلة في هذا الطلب", timeline: "مراحل الطلب", trackingNumber: "رقم التتبع", verifyHint: "البريد أو الهاتف المستخدم عند الطلب" },
    wishlist: { emptyBody: "اضغط على القلب في أي منتج ليُحفظ هنا.", emptyTitle: "قائمة أمنياتك فارغة" },
  },
  he: {
    common: { breadcrumbs: "מסלול ניווט", demoBanner: "מצב דמו — קטלוג לדוגמה ותשלום מדומה לתצוגה בלבד. אין הזמנות, תשלומים או הודעות אמיתיים.", demoFooterNote: "פועל במצב דמו — נתוני פיתוח בלבד.", demoLabel: "דמו", language: "שפה", select: "בחר…", signupThanks: "תודה — נוספת לרשימה.", viewAll: "לכל הפריטים" },
    about: { intro: "CROWNED היא יעד אצור לחולצות כדורגל — אייקוני רטרו ומדי העונה הנוכחית, נבחרים בקפידה עם משלוח לכל הארץ.", body1: "התחלנו מרעיון פשוט: החולצות שהגדירו תקופות ראויות ליותר ממרקטפלייס עמוס. כל פריט בקטלוג נבחר בזכות הסיפור שלו — עונה, גמר, או צבעים שאנשים זוכרים.", body2: "כל הזמנה מיוצרת לפי דרישה: בוחרים מידה, גרסה והתאמה אישית, ואנחנו דואגים לייצור ומעדכנים בכל שלב עד הדלת." },
    account: { confirmEmail: "בדקו את המייל לאישור החשבון ואז התחברו.", demoHint: "חשבונות דמו לתצוגה:", emailTaken: "כבר קיים חשבון עם המייל הזה.", invalidCredentials: "אימייל או סיסמה שגויים.", passwordHint: "לפחות 8 תווים.", profileTab: "פרופיל", registerValidation: "נא למלא שם תקין, אימייל תקין וסיסמה של 8+ תווים." },
    cart: { deliveryAtCheckout: "מחושב בקופה" },
    checkout: { confirmations: "אישורים", days: "ימים", demoPaymentNote: "מצב דמו: התשלום מדומה לתצוגה בלבד. לא מתבצע תשלום אמיתי ולא עובר כסף.", fixErrors: "נא לתקן את הבאים:", free: "חינם", manualVerification: "אימות ידני", marketingConsent: "עדכנו אותי על דרופים חדשים (רשות).", noMethods: "אין כרגע אמצעי תשלום זמינים. כתבו לנו בוואטסאפ.", policyAckRequired: "נא לאשר את מדיניות החנות כדי להמשיך.", selectPayment: "נא לבחור אמצעי תשלום.", selectZone: "נא לבחור אזור משלוח.", selectZoneShort: "בחרו אזור", simulatedDemo: "מדומה (דמו)", zone: "אזור משלוח", error_generic: "משהו השתבש בביצוע ההזמנה. נסו שוב.", error_payment_method_unavailable: "אמצעי התשלום אינו זמין.", error_zone_unavailable: "אזור המשלוח שנבחר אינו זמין.", error_empty_cart: "העגלה ריקה.", error_product_unavailable: "מוצר בעגלה אינו זמין יותר.", error_invalid_size: "המידה שנבחרה אינה זמינה.", error_invalid_version: "הגרסה שנבחרה אינה זמינה.", error_invalid_sleeve: "אפשרות השרוול אינה זמינה.", error_invalid_patch: "הפאץ' שנבחר אינו זמין.", error_invalid_quantity: "כמות לא תקינה.", error_personalization_unavailable: "התאמה אישית אינה זמינה למוצר בעגלה.", error_invalid_personalization: "שם או מספר לא תקינים." },
    confirmation: { bankNote: "ההזמנה תעבור להכנה מיד עם אימות ההעברה (בדרך כלל תוך יום עסקים).", nextSteps: "קיבלנו את ההזמנה. תקבלו עדכונים לאורך הייצור, השילוח והמסירה — ואפשר לבדוק סטטוס בכל רגע." },
    contact: { intro: "שאלה על הזמנה, מידה או חולצה מסוימת? הדרך המהירה היא וואטסאפ — או השאירו הודעה כאן.", message: "הודעה", received: "ההודעה התקבלה — נחזור אליכם בקרוב.", send: "שליחה", validation: "נא למלא שם, פרט קשר תקין והודעה." },
    delivery: { eta: "זמן מסירה מקומי", etaClarification: "הערכת 10–14 הימים מתחילה בשילוח הספק, לא בסיום ההזמנה.", internationalTitle: "משלוח בינלאומי", intro: "אנחנו שולחים לכל הארץ באזורי משלוח הניתנים להגדרה. משלוח חינם מ־3 פריטים מזכים.", joinWaitlist: "הצטרפו לרשימת ההמתנה", zone: "אזור", zonesTitle: "אזורי משלוח" },
    errors: { confirmSize: "נא לאשר שבדקתם את טבלת המידות.", confirmSpelling: "נא לאשר את איות ההתאמה האישית.", invalidName: "שם: אותיות בלבד, עד 14 תווים.", invalidNumber: "מספר: ספרה או שתיים." },
    faq: { intro: "תשובות מהירות על הזמנה, מידות, משלוח והחזרות.", q1: "כמה זמן לוקח המשלוח?", a1: "ההזמנות מיוצרות לפי דרישה. לאחר שילוח הספק, המשלוח אורך כ־10–14 ימים, בתוספת זמן מסירה מקומי באזורכם.", q2: "איך מקבלים משלוח חינם?", a2: "מוסיפים 3 פריטים מזכים או יותר — לפי מספר פריטים, לא לפי סכום.", q3: "השם והמספר באמת בחינם?", a3: "כן. התאמת שם ומספר בחינם; פאץ' אופציונלי מוסיף ₪5.", q4: "איזו מידה לקחת?", a4: "בדקו את מדריך המידות בכל עמוד מוצר — הטבלאות שונות בין אוהד, שחקן, רטרו, שרוול ארוך, הודי וילדים. גרסת שחקן צמודה.", q5: "אפשר לבטל או להחזיר?", a5: "ביטול אפשרי רק לפני תחילת הייצור. מכיוון שהפריטים מיוצרים לפי הזמנה, בדרך כלל אין החזרות על טעות במידה או שינוי דעה — ראו את המדיניות המלאה.", q6: "מה אם ההזמנה הגיעה פגומה או שגויה?", a6: "צרו קשר תוך 48 שעות מהמסירה עם תמונות ברורות — נבחן ונספק החלפה או פתרון מתאים במקרים המתאימים.", q7: "איך משלמים?", a7: "כרגע בהעברה בנקאית (מאומתת ידנית לפני ייצור). אמצעי תשלום נוספים בקרוב.", q8: "איך עוקבים אחרי ההזמנה?", a8: "בעמוד מעקב ההזמנות עם מספר ההזמנה והאימייל או הטלפון מההזמנה." },
    filters: { adults: "מבוגרים", audience: "מיועד ל", between150200: "₪150–₪200", clear: "ניקוי מסננים", era: "תקופה", more: "עוד", over200: "מעל ₪200", personalizable: "עם התאמה אישית", price: "מחיר", sort: "מיון", sortFeatured: "מומלצים", sortNewest: "החדשים ביותר", sortPriceAsc: "מחיר: מהנמוך", sortPriceDesc: "מחיר: מהגבוה", title: "מסננים", under150: "עד ₪150" },
    footer: { accessibility: "הצהרת נגישות", delivery: "משלוחים", faq: "שאלות נפוצות", howOrdering: "איך ההזמנה עובדת", privacy: "מדיניות פרטיות", returnsPolicy: "ביטולים והחזרות", terms: "תנאי שימוש" },
    home: { fanCardTitle: "נוחות יומיומית", fanPoint1: "גזרה רגילה ומשוחררת", fanPoint2: "בד רך יותר ליומיום", fanPoint3: "הבחירה הקלאסית ליציע", playerCardTitle: "כמו ביום משחק", playerPoint1: "גזרה אתלטית צמודה", playerPoint2: "בד משחק קל ומאוורר", playerPoint3: "פרטים כפי שנלבשים על הדשא", personalizationDetail: "השם והמספר שלך מודפסים חינם על כל חולצה עם התאמה אישית. פאץ' בסגנון רשמי ב־₪5.", trustDeliveryTitle: "משלוח לכל הארץ", trustDeliveryBody: "כ־10–14 ימים משילוח הספק", trustQualityTitle: "גימור אמיתי", trustQualityBody: "איכות רפליקה גבוהה, נבדקת לפני שילוח", trustSupportTitle: "תמיכה אמיתית", trustSupportBody: "כתבו לנו בוואטסאפ על מידות, הזמנות וכל דבר אחר", step1Title: "בוחרים חולצה", step1Body: "מידה, גרסה, שרוול — ושם ומספר בחינם.", step2Title: "מאשרים הזמנה", step2Body: "תשלום אונליין או שריון בהעברה בנקאית.", step3Title: "אנחנו מייצרים", step3Body: "הפריט מיוצר לפי הזמנה ועובר בדיקת איכות.", step4Title: "מגיע עד אליך", step4Body: "כ־10–14 ימים מהשילוח, עם מעקב מלא." },
    how: { intro: "כל פריט של CROWNED מיוצר לפי הזמנה. הנה בדיוק מה שקורה אחרי ההזמנה — בלי הפתעות.", etaNote: "הערכת 10–14 הימים מתחילה כשהספק משלח את ההזמנה — לא בסיום הקנייה. אפשר לעקוב אחרי כל שלב בעמוד המעקב.", step1Title: "ההזמנה התקבלה", step1Body: "ההזמנה וההתאמה האישית נרשמות בדיוק כפי שהוזנו.", step2Title: "התשלום אושר", step2Body: "תשלום אונליין מאושר אוטומטית; העברה בנקאית מאומתת ידנית.", step3Title: "נשלח לספק", step3Body: "ההזמנה מוכנה ועוברת לייצור.", step4Title: "ייצור", step4Body: "החולצה מיוצרת עם המידה, הגרסה וההדפסה שלך.", step5Title: "שילוח הספק", step5Body: "ההזמנה יוצאת מהייצור — מכאן מתחיל חלון 10–14 הימים.", step6Title: "בדרך", step6Body: "בדרכה לארץ.", step7Title: "מסירה מקומית", step7Body: "הגיעה לארץ ובדרך אליך.", step8Title: "נמסר", step8Body: "תהנו — ותייגו אותנו, אנחנו אוהבים לראות חולצות ברחוב." },
    issues: { category: "סוג הבעיה", contact: "אימייל או טלפון", description: "מה קרה?", intro: "אם ההזמנה הגיעה פגומה, לקויה או שגויה — ספרו לנו תוך 48 שעות מהמסירה עם תמונות ברורות ונתקן במקרים המתאימים.", photo: "תמונות", photoHint: "תמונות ברורות עוזרות לפתור מהר יותר.", received: "הדיווח התקבל — נבדוק ונחזור אליכם.", resolution: "הפתרון המבוקש", resolutionHint: "למשל: החלפה", submit: "שליחת דיווח", validation: "נא למלא שם, פרט קשר ותיאור (10+ תווים).", cat_damaged: "מוצר פגום", cat_defective: "מוצר לקוי", cat_incorrect_item: "פריט שגוי", cat_incorrect_size_supplied: "סופקה מידה שגויה", cat_incorrect_personalization: "התאמה אישית שגויה", cat_missing_item: "פריט חסר", cat_delivery_problem: "בעיית משלוח", cat_other: "אחר" },
    policy: { legalReviewNote: "טיוטה — ממתינה לבדיקה משפטית מקצועית לפני השקה." },
    product: { careBody: "כביסה קרה במכונה כשהחולצה הפוכה. בלי מייבש, בלי גיהוץ ישיר על הדפסות ותגים.", freeLabel: "חינם", galleryThumbs: "תמונות מוצר", patchNone: "בלי פאץ'", priceUpdatesNote: "המחיר מתעדכן לפי הבחירות", zoomImage: "הגדלת תמונה", versionKids: "ילדים", versionRetro: "רטרו" },
    reviews: { displayName: "שם לתצוגה", moderationNote: "ביקורות מתפרסמות לאחר אישור. הימנעו מפרטים אישיים.", pageIntro: "משוב אמיתי מלקוחות CROWNED. רשומות דמו מסומנות וקיימות רק בגרסת התצוגה.", photoAlt: "תמונה מאת {name}", photoInvalid: "תמונה: JPG/PNG/WebP עד 4MB.", photoLabel: "הוסיפו תמונה (רשות)", reviewTitle: "כותרת" },
    search: { hint: "חפשו לפי קבוצה, תקופה, עונה או סוג — למשל “רטרו 2005” או “הודי”.", placeholder: "חיפוש חולצות…", resultsFor: "{count} תוצאות עבור “{query}”", tryThese: "אין התאמות מדויקות — אולי אחד מאלה:" },
    shop: { metaDescription: "הקטלוג המלא של CROWNED — אייקוני רטרו, מדי העונה, נבחרות, הודיס וסטים לילדים.", noResults: "שום דבר לא מתאים למסננים", noResultsBody: "נסו להסיר מסנן או שניים — או חפשו משהו אחר.", resultCount: "{count} פריטים" },
    sizeGuide: { chest: "חזה (שטוח)", length: "אורך", placeholderNote: "טבלה ראשונית — המידות הסופיות יאושרו לפני ההשקה.", variesNote: "מידות משתנות בין סוגי מוצרים — בדקו תמיד את הטבלה של הפריט הספציפי." },
    tracking: { carrierLink: "מעקב חברת שילוח", estimatedDelivery: "מסירה משוערת", intro: "הזינו את מספר ההזמנה יחד עם האימייל או הטלפון מההזמנה.", items: "פריטים", metaDescription: "מעקב מאובטח אחרי הזמנת CROWNED עם מספר הזמנה ופרטי קשר.", reportIssue: "דיווח על בעיה בהזמנה", timeline: "התקדמות ההזמנה", trackingNumber: "מספר מעקב", verifyHint: "האימייל או הטלפון שבהזמנה" },
    wishlist: { emptyBody: "הקישו על הלב בכל מוצר כדי לשמור אותו כאן.", emptyTitle: "רשימת המשאלות ריקה" },
  },
};

function deepMerge(target, patch) {
  for (const [key, value] of Object.entries(patch)) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      target[key] = target[key] ?? {};
      deepMerge(target[key], value);
    } else {
      target[key] = value;
    }
  }
}

for (const locale of ["en", "ar", "he"]) {
  const path = `src/lib/i18n/${locale}.json`;
  const dict = JSON.parse(readFileSync(path, "utf8"));
  deepMerge(dict, ADD[locale]);
  writeFileSync(path, `${JSON.stringify(dict, null, 2)}\n`);
  console.log(`${locale}: merged`);
}
